######################
## Crafting Section ##
######################

customCrafting: false
########################################################################
## If custom crafting is true choose what custom crafting you want on ##
########################################################################
## Custom Weapons ##
####################
trident: true
spatha: true
pitchfork: true
sunBow: true
moonBow: true



#################
## Join/Leave ##
#################
joinMessage: p% joined the game!
leaveMessage: p% left the game!
fireworkOnJoin: false

##################
##  Demi GUI    ##
## Rank Control ##
##################
demiGUI: true
ZeusRankName: Zeus
JupiterRankName: Jupiter
PoseidonRankName: Poseidon
NeptuneRankName: Neptune
HadesRankName: Hades
PlutoRankName: Pluto