##############
## Crafting ##
##############
customCrafting: true

#################
## Join/Leave ##
#################
joinMessage: p% joined the game!
leaveMessage: p% left the game!
fireworkOnJoin: false

##################
##  Demi GUI    ##
## Rank Control ##
##################
demiGUI: true
ZeusRankName: Zeus
JupiterRankName: Jupiter
PoseidonRankName: Poseidon
NeptuneRankName: Neptune
HadesRankName: Hades
PlutoRankName: Pluto